# modules/narrative.py
import pandas as pd

def generate_case_narrative(case_df: pd.DataFrame, label_col: str) -> str:
    num_events = len(case_df)
    label_value = case_df[label_col].iloc[-1] if label_col in case_df.columns and not case_df.empty else None
    narrative = f"*Example narrative (placeholder)*:\n\nThis case contains **{num_events}** events. "
    if label_value is not None:
        narrative += f"The final outcome label is **{label_value}**. "
    narrative += "In the final implementation, this text will be generated by an LLM."
    return narrative
